import { useAddress, useContract, useMetamask } from "@thirdweb-dev/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const connectUsingMetamask = useMetamask();
  const address = useAddress();
  const customContract = useContract(
    "0xF647707E50c306E8579Bf1d059865a5870A72652"
  );

  const getNumber = async () => {
    const number = await customContract.contract.functions.getNumber();
    alert(`Number is ${number}`);
  };

  const incrementNumber = async () => {
    const request = await customContract.contract.functions.increment();
    await request.wait();
    alert(`Done!`);
  };

  const decrementNumber = async () => {
    const request = await customContract.contract.functions.decrement();
    await request.wait();
    alert(`Done!`);
  };

  useEffect(() => {
    if (!customContract) return;
    setLoading(false);
    console.log(customContract);
  }, [customContract]);

  return (
    <div className="screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <div>Loading...</div>
      ) : address ? (
        <div>
          <button className="button" onClick={getNumber}>
            Get Number
          </button>
          <button className="button" onClick={incrementNumber}>
            Increment
          </button>
          <button className="button" onClick={decrementNumber}>
            Decrement
          </button>
        </div>
      ) : (
        <div>
          <button className="button" onClick={connectUsingMetamask}>
            Connect using metamask
          </button>
        </div>
      )}
    </div>
  );
}
